# Generated by Django 4.1.1 on 2022-09-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=30, null=True)),
                ('start_size', models.CharField(blank=True, max_length=100, null=True)),
                ('start_price', models.CharField(blank=True, max_length=100, null=True)),
                ('down_payment', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_plan', models.CharField(blank=True, max_length=30, null=True)),
                ('dld', models.CharField(blank=True, max_length=30, null=True)),
                ('service_charge', models.CharField(blank=True, max_length=30, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commision', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.builder')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectimages', to='project.project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
