# Generated by Django 4.1.1 on 2022-09-19 15:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManager',
            fields=[
            ],
            options={
                'verbose_name': 'Sale manager',
                'verbose_name_plural': 'Sale Managers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='addr'),
        ),
    ]
