# Generated by Django 4.1.1 on 2022-10-03 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_budget_alter_user_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_users', to=settings.AUTH_USER_MODEL, verbose_name='left_user')),
                ('right_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_users', to=settings.AUTH_USER_MODEL, verbose_name='right_user')),
            ],
        ),
    ]
