# Generated by Django 4.1.1 on 2022-10-03 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_relatedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
