# Generated by Django 4.1.1 on 2022-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
