# Generated by Django 4.1.1 on 2022-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_navigation_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='url',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='slug',
        ),
        migrations.AddField(
            model_name='navigation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigation',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
