# Generated by Django 4.1.1 on 2022-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_rename_url_navigation_key_remove_navigation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='noCollaps',
            field=models.BooleanField(default=0),
        ),
    ]
