# Generated by Django 4.1.1 on 2022-12-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_navigation_nocollaps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='noCollaps',
            new_name='noCollapse',
        ),
    ]
