# Generated by Django 4.1.1 on 2022-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('default', '0005_rename_nocollaps_navigation_nocollapse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='noCollapse',
            new_name='no_collapse',
        ),
        migrations.AddField(
            model_name='navigation',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='navgation_set', related_query_name='navigation', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
