# Generated by Django 4.1.1 on 2022-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_rename_nocollapse_navigation_no_collapse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='order',
            field=models.FloatField(default=0.0),
        ),
    ]
